<a href="https://colab.research.google.com/github/Parsival1/Analisis_de_datos/blob/main/Taller%204%20-%20Arbol%20de%20clasificacion/Modelo_arbol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Gestion de librerias#

In [ ]:
#importar las librerias

# Procesar la informacion
import pandas as pd
import numpy as np

# Visualizacion del arbol
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

# Regresion Logistica
from sklearn.tree import DecisionTreeClassifier #
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

# Evaluacion del Modelo
from sklearn.metrics import accuracy_score, confusion_matrix

# Encriptacion de modelo
import pickle

#Lectura y procesaiento de datos#

In [ ]:
dataset = pd.read_excel('agricultura.xlsx')

In [ ]:
#Obtener informacion del dataset - Etiquetas
dataset.info()

In [ ]:
# Mezclar los datos
dataset = shuffle(dataset, random_state=1)

#Entrenamiento de datos#

In [ ]:
# Seleccionar las variables relevantes
variables = ['N', 'P', 'K', 'temperatura','humedad','ph','precipitacion']

X = dataset[variables]
y = dataset['etiqueta']

In [ ]:
# Dividir el conjunto de datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [ ]:
# Crear el modelo de Clasificacion
model = DecisionTreeClassifier(random_state=10)

In [ ]:
# Entrenar el modelo
model.fit(X_train, y_train)

In [ ]:
# Realizar predicciones en el conjunto de prueba
y_pred = model.predict(X_test)

In [ ]:
# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print('Precisión del modelo: %.2f' % accuracy)

Precisión del modelo: 0.96


In [ ]:
# Calcular la matriz de confusión
conf_matrix = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(conf_matrix)

Matriz de confusión:
[[19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  2  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1 27  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0 23  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  1  0  0 23  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0]
 [ 0  0  0  0

In [ ]:
plt.figure(figsize=(12, 8))
plot_tree(model, feature_names=dataset.columns[:-1], class_names=model.classes_, filled=True, rounded=True)
plt.show()

In [ ]:
N = 13
P = 5
K = 8
temperatura = 2385340379
humedad = 9010522549
ph = 7474710503
precipitacion = 103923226

In [ ]:
# Valores futuros
new_samples = np.array([[N, P, K, temperatura,humedad,ph,precipitacion]])

# Realiza predicciones en las nuevas muestras utilizando el modelo de árbol de decisión
y_pred_new = model.predict(new_samples)

print(f"La semilla perfecta para sembras en su terreno es: {y_pred_new[0]}")

La semilla perfecta para sembras en su terreno es: naranja


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


#Exportacion de datos#

In [ ]:
# Guardar el modelo en un archivo
with open('modelo_arbol.pkl', 'wb') as file:
    pickle.dump(model, file)